Algoritmo "semnome"
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/04/2024
Var

n1 : inteiro

Inicio

escreval("Digite um número e diremos se ele está no intervalo de 100 a 200")
leia(n1)

se (n1 >= 100) e (n1 <= 200) entao

escreval("O número",n1, " está dentro do intervalo entre 100 e 200(incluso)")

senao

escreval("O número",n1, " não está no intervalo entre 100 e 200(incluso)")
fimse

Fimalgoritmo