Algoritmo "semnome"
// Disciplina: [Linguagem e Lógica de Programação]
// Professor: Clenio Emidio
// Descrição: Aqui você descreve o que o programa faz! (função)
// Autor(a): Luiz Henrique Maciel de Oliveira
// Data atual: 11/03/2024
Var

A , B , i: real

Inicio

escreval("Digite o valor de A")
leia(A)

escreval("Digite o valor de B")
leia(B)



i <- A
A <- B
B <- i

escreval("")
escreval("Ao invertermos teremos o valor de A sendo:", A)
escreval("E o valor de B sendo:", B)
Fimalgoritmo