Algoritmo "semnome"
// Disciplina: [Linguagem e Lógica de Programação]
// Professor: Clenio Emidio
// Descrição: Aqui você descreve o que o programa faz! (função)
// Autor(a): Luiz Henrique Maciel de Oliveira
// Data atual: 11/03/2024
Var

Celsius : real

Inicio

escreva("Digite a temperatura em graus Celsius: ")

leia(Celsius)

escreval("")
escreval(Celsius , "ºC equivalem a" , (9*Celsius+160)/5 , "ºF")

Fimalgoritmo