Algoritmo "semnome"
// Disciplina: [Linguagem e Lógica de Programação]
// Professor: Clenio Emidio
// Descrição: Aqui você descreve o que o programa faz! (função)
// Autor(a): Luiz Henrique Maciel de Oliveira
// Data atual: 11/03/2024
Var

valorInvest, montante : real

Inicio

escreval("Digite o valor que deseja depositar: ")

leia(valorInvest)

montante <- valorInvest + (valorInvest * 0.007 * 3)

escreval("Após três meses, o montante total será de: " , montante , " reais")



Fimalgoritmo